let DATA={events:[],deadlines:[]},filter="all",showPast=false;
const $=s=>document.querySelector(s),pad=n=>String(n).padStart(2,"0");
const fmtDate=d=>new Intl.DateTimeFormat("vi-VN",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(d));
function parts(ms){if(ms<=0)return null;let s=Math.floor(ms/1000);return{d:Math.floor(s/86400),h:Math.floor(s%86400/3600),m:Math.floor(s%3600/60),s:s%60}}
function clockHTML(ms,target){let t=parts(ms);return `<div class="countdown" data-countdown data-target="${target}">${t?unitHTML(t):'<div class="unit"><b>00</b><small>ĐÃ ĐẾN HẠN</small></div>'}</div>`}
function unitHTML(t){return `<div class="unit"><b>${t.d}</b><small>NGÀY</small></div><div class="unit"><b>${pad(t.h)}</b><small>GIỜ</small></div><div class="unit"><b>${pad(t.m)}</b><small>PHÚT</small></div><div class="unit"><b>${pad(t.s)}</b><small>GIÂY</small></div>`}
function eventRange(e){return e.endDate?`${fmtDate(e.date)} – ${fmtDate(e.endDate)}`:fmtDate(e.date)}
function makeEvent(e){return{...e,kind:"event",ts:new Date(e.date).getTime()}}
function makeDeadline(d){return{...d,kind:"deadline",ts:new Date(d.date).getTime()}}
function clockInline(ms){let t=parts(ms);return t?`${t.d} ngày · ${pad(t.h)} giờ · ${pad(t.m)} phút · ${pad(t.s)} giây còn lại`:"ĐÃ QUA DEADLINE"}
function eventCard(e){let v=e.type==="VEX V5"?"v5":"iq",ms=e.ts-Date.now(),past=ms<=0,details=(e.details||[]).map(x=>`<div>${x}</div>`).join("");let attached=(e.notebook||[]).map(n=>{let target=new Date(n.date).getTime();return `<div class="deadline"><div class="deadline-box"><div class="deadline-title">NOTEBOOK DEADLINE</div><div class="deadline-name">${n.label}</div><div class="deadline-clock" data-inline-target="${target}">${clockInline(target-Date.now())}</div><div class="deadline-note">${n.display||fmtDate(n.date)}</div></div></div>`}).join("");return `<div class="card" tabindex="0"><div class="date-label">${eventRange(e)}</div><h3>${e.title}</h3><div class="place">${e.place||""}</div><div class="link"><a href=${e.link||""} target="_blank">Link Event</a></div>${clockHTML(ms,e.ts)}<div class="details">${details}</div><div class="card-footer"><span class="type">${e.type}</span><span class="past-label">${past?"ĐÃ DIỄN RA":"COUNTING DOWN"}</span></div>${attached}</div>`}
function deadlineCard(d){let ms=d.ts-Date.now();return `<div class="card" tabindex="0"><div class="date-label">NOTEBOOK DEADLINE · ${fmtDate(d.date)}</div><h3>${d.title}</h3><div class="place">Giải đấu: ${d.forEvent||"Panda Robotics"}</div>${clockHTML(ms,d.ts)}<div class="card-footer"><span class="type">${d.type}</span><span class="past-label">${ms<=0?"ĐÃ QUA DEADLINE":"CẦN HOÀN THÀNH"}</span></div></div>`}
function render(){let all=[...DATA.events.map(makeEvent),...DATA.deadlines.map(makeDeadline)].filter(x=>filter==="all"||x.type===filter).filter(x=>showPast||x.ts>Date.now()).sort((a,b)=>a.ts-b.ts);let host=$("#items");host.innerHTML="";all.forEach((e,i)=>{let wrap=document.createElement("article"),right=i%2===1;wrap.className=`item ${right?"right":""} ${e.type==="VEX V5"?"v5":"iq"} ${e.kind==="deadline"?"deadline-only":""}`;wrap.innerHTML=`<span class="node"></span>${e.kind==="deadline"?deadlineCard(e):eventCard(e)}`;host.appendChild(wrap)});observe();updateClocks()}
let observer;function observe(){if(observer)observer.disconnect();observer=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add("visible");observer.unobserve(x.target)}}),{threshold:.12});document.querySelectorAll(".item").forEach(x=>observer.observe(x))}
function updateClocks(){document.querySelectorAll("[data-countdown]").forEach(el=>{let t=parts(Number(el.dataset.target)-Date.now());el.innerHTML=t?unitHTML(t):'<div class="unit"><b>00</b><small>ĐÃ ĐẾN HẠN</small></div>'});document.querySelectorAll("[data-inline-target]").forEach(el=>el.textContent=clockInline(Number(el.dataset.inlineTarget)-Date.now()))}
function tick(){updateClocks()}
document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{filter=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));render()}));
$("#showPast").addEventListener("change",e=>{showPast=e.target.checked;render()});
fetch("events.json",{cache:"no-store"}).then(r=>{if(!r.ok)throw Error("events.json load failed");return r.json()}).then(d=>{DATA=d;render();setInterval(tick,1000)}).catch(e=>{$("#items").innerHTML='<p class="empty">Không tải được events.json. Kiểm tra file và vị trí trong repository.</p>';console.error(e)});
